required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen"
]

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.4"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.4"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.7.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.4.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
